import Head from 'next/head'
import Banner from '../Components/Banner/Banner';
import HomeLayout from '../Components/Layout/HomeLayout';
import Styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <HomeLayout>
      <Head>
        <title>Tasnia Tamanna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    </HomeLayout>
  )
}
